// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8Cfv0up8Mlbjt5AFDn__5VbYv9v9504',
    appId: '1:622361279886:web:6a35a3f9fd09e1b2e538df',
    messagingSenderId: '622361279886',
    projectId: 'notes-cc287',
    authDomain: 'notes-cc287.firebaseapp.com',
    storageBucket: 'notes-cc287.firebasestorage.app',
    measurementId: 'G-QLD2G1Y12E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZO43bAOimifsGx4SukfTrBJ3fMJn82yw',
    appId: '1:735719548939:android:add10b201720c674a07f0e',
    messagingSenderId: '735719548939',
    projectId: 'notesapp-ec07d',
    storageBucket: 'notesapp-ec07d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm6HCZCeK2din2BcD2kdKg9pfMPAS5ZLk',
    appId: '1:622361279886:ios:cf5302c962172e8ee538df',
    messagingSenderId: '622361279886',
    projectId: 'notes-cc287',
    storageBucket: 'notes-cc287.firebasestorage.app',
    iosBundleId: 'com.app.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm6HCZCeK2din2BcD2kdKg9pfMPAS5ZLk',
    appId: '1:622361279886:ios:cf5302c962172e8ee538df',
    messagingSenderId: '622361279886',
    projectId: 'notes-cc287',
    storageBucket: 'notes-cc287.firebasestorage.app',
    iosBundleId: 'com.app.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp8Cfv0up8Mlbjt5AFDn__5VbYv9v9504',
    appId: '1:622361279886:web:868037d59b431ab0e538df',
    messagingSenderId: '622361279886',
    projectId: 'notes-cc287',
    authDomain: 'notes-cc287.firebaseapp.com',
    storageBucket: 'notes-cc287.firebasestorage.app',
    measurementId: 'G-51CDDPSZ6D',
  );
}
